ALTER TABLE scenario_metrics
    ADD COLUMN IF NOT EXISTS total_loco_distance_meters DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS empty_loco_distance INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS empty_loco_distance_meters DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS loaded_loco_distance INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS loaded_loco_distance_meters DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_wagons_moved INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_wagon_distance INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS total_wagon_distance_meters DOUBLE PRECISION NOT NULL DEFAULT 0;
